### ISSUE TITLE
Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by Alessevan** [mlbonniec/bild#13]
Hello, when I want to send a picture to the server, I have theses errors which appear.
```
::ffff:194.163.159.48 - - [19/Aug/2021:16:34:54 +0000] "POST /api/v1/contents HTTP/1.0" 500 35
Error: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:371:5)
    at ServerResponse.setHeader (node:_http_outgoing:573:11)
    at ServerResponse.header (/var/www/bild/node_modules/express/lib/response.js:771:10)
    at ServerResponse.send (/var/www/bild/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/var/www/bild/node_modules/express/lib/response.js:267:15)
    at ServerResponse.res.success (/var/www/bild/src/middlewares/message.ts:11:28)
    at /var/www/bild/src/controllers/contents/post.ts:52:20
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
Error: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:371:5)
    at ServerResponse.setHeader (node:_http_outgoing:573:11)
    at ServerResponse.header (/var/www/bild/node_modules/express/lib/response.js:771:10)
    at ServerResponse.send (/var/www/bild/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/var/www/bild/node_modules/express/lib/response.js:267:15)
    at ServerResponse.res.error (/var/www/bild/src/middlewares/message.ts:24:28)
    at /var/www/bild/src/controllers/contents/post.ts:54:20
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
NPM version : 7.20.3
Node version : 16.6.2
Ubuntu 20.04
Branch : master

I receive @Romitou 's help : we have all modules, node and npm with the same version but he doesn't have these errors.

**Comment by Alessevan** [comment]
I succeed to resolve the problem by passing to Node 12 and reset my mongodb.
I use a non root user too.
